-- as admin account
CREATE SCHEMA "POC_SECU";
CREATE ROLE ZFULLACCESSPOC_SECU;
GRANT "CREATE ANY",ALTER,INSERT,DELETE,UPDATE,SELECT,DROP ON SCHEMA "POC_SECU" to "ZFULLACCESSPOC_SECU";
GRANT ZFULLACCESSPOC_SECU to RA;	-- MY USER
--drop table "POC_SECU"."APPRO_USER_MNGT";		-- if need to rebuild
CREATE ROW TABLE "POC_SECU"."APPRO_USER_MNGT" ( "USERID" NVARCHAR(12) NOT NULL,
	 "ENABLED" DECIMAL(1) NOT NULL,
	 "ROLES" NVARCHAR(256),
	 "TO_UPDATE" DECIMAL(1) NOT NULL,
	 "TO_DISABLE" DECIMAL(1) NOT NULL,
	 "TO_ENABLE" DECIMAL(1) NOT NULL,
	 "TO_DELETE" DECIMAL(1) NOT NULL,
	 "LAST_CHANGE_DATE" DATE,
	 "LAST_CHANGE_TIME" TIME,
	 PRIMARY KEY ("USERID"));

--drop table "POC_SECU"."APPRO_USER_HISTORY";	 	-- if need to rebuild
CREATE ROW TABLE "POC_SECU"."APPRO_USER_HISTORY" ( "ZDATE" DATE,
	"ZTIME" TIME,
	"USERID" NVARCHAR(12) NOT NULL,
	"ACTION" NVARCHAR(32),
	"ROLES" NVARCHAR(256),
	"COMMENT" NVARCHAR(256) );

